spring:
  config:
    import: application-secret.yml

  jpa:
    hibernate:
      ddl-auto: create   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB      # 개별 파일 최대 크기
      max-request-size: 100MB  # 전체 요청 최대 크기 (다중 업로드 고려)

  # TODO: 임시로 로컬 파일 시스템 사용 - 추후 S3로 변경 예정
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

logging:
  level:
    org.hibernate.SQL: debug